
# code: language=Dockerfile
FROM python:3.7
WORKDIR /app
RUN \
  apt-get -y update && \
  apt-get -y install --no-install-recommends \
    dnsutils \
    mysql-client \
    postgresql-client \
    && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists && \
  true
COPY setup/requirements.txt ./
COPY setup.py ./
COPY dojo/ ./dojo/
RUN pip wheel --wheel-dir=/tmp/wheels -r ./requirements.txt .
