version: '3'
services:

  broker:
    image: redis:5.0.2-alpine
    ports:
      - "6379:6379"

  db:
    image: postgres
    env_file:
      - ./env/postgres.env
    ports:
      - "5432:5432"

  init:
    build:
      context: "."
    ports:
      - "8000:8000"
    depends_on:
      - db
      - broker
    env_file:
      - ./env/dojo.env
    command: ./wait-for-it.sh db:5432 -- ./docker-start.bash -i

  django1:
    build:
      context: "."
    ports:
    - "8001:8000"
    depends_on:
    - db
    - broker
    - init
    env_file:
      - ./env/dojo.env
    command: ./wait-for-it.sh db:5432 -- ./docker-start.bash -s

  django2:
    build:
      context: "."
    ports:
    - "8002:8000"
    depends_on:
    - db
    - broker
    - init
    env_file:
      - ./env/dojo.env
    command: ./wait-for-it.sh db:5432 -- ./docker-start.bash -s

  worker:
    build:
      context: "."
    depends_on:
      - init
      - broker
    env_file:
      - ./env/dojo.env
    command: ./wait-for-it.sh db:5432 -- ./docker-start.bash -c

