#!/usr/bin/env python

from setuptools import setup

setup(
    name='DefectDojo',
    version='1.5.4',
    author='Greg Anderson',
    description="Tool for managing vulnerability engagements",
    install_requires=[
        'celery',
        'defusedxml',
        'Django>=2.0.10',
        'django_celery_results>=1.0.4',
        'django-auditlog>=0.4.0',
        'django-custom-field',
        'django-filter>=1.0.4',
        'django-imagekit',
        'django-multiselectfield',
        'django-overextends>=0.4.3',  # Required for extensions
        'django-polymorphic>=2.0',
        'django-rest-swagger>=2.1.2',
        'django-slack',
        'django-tagging',
        'django-taggit-serializer>=0.1.7',
        'django-tastypie-swagger',
        'django-tastypie>=0.12.2',
        'django-watson>=1.3.1',
        'django-rest-swagger>=2.1.2',
        'djangorestframework>=3.7.7',
        'django-environ>=0.4.5',
        'django-dbbackup>=3.2.0',
        'django-markdownx>=2.0.23',
        'html2text',
        'humanize',
        'jira',
        'lxml',
        'Pillow',
        'pycrypto',
        'python-nmap>=0.3.4',
        'pytz>=2013.9',
        'requests>=2.2.1',
        'sqlalchemy',  # Required by Celery broker transport
        'vobject',
        'html2text',
        'django-watson',
        'sqlalchemy',
        'pdfkit>=0.6.1',
        'defusedxml',
        'pbr',
        'asteval',
        'Markdown>=3.0.1',
        'pandas>=0.22.0',
        'whitenoise>=4.0',
        'gunicorn>=19.7.1',
        'mysql-connector-python>=8.0.14',
        'mysqlclient>=1.3.12',
        'psycopg2-binary>=2.7.5',
        'django-filter>=1.0.4',
        'python-dateutil==2.6.0',
        'bleach==3.1.0',
        'bleach_whitelist==0.0.10',
        'uWSGI>=2.0.18',
        'redis>=3.2.0',
    ],
    url='https://github.com/DefectDojo/django-DefectDojo'
)
